modLoader="javafml"
loaderVersion="[39,)"
license="GNU GPLv3"

[[mods]]
modId="tumbleweed"
version="1.18-0.4.11" # Remember to update in build.gradle
displayName="Tumbleweed"
logoFile="logo.png"
authors="konwboy"
description='Tumbleweeds spawn around dead bushes in deserts. They drop random goodies upon destroying.'
