modLoader="javafml"
loaderVersion="[41,)"
license="GNU LGPLv3"

[[mods]]
modId="tumbleweed"
version="1.19-0.4.13" # Remember to update in build.gradle
displayName="Tumbleweed"
logoFile="logo.png"
authors="konwboy"
description='Tumbleweeds spawn around dead bushes in deserts. They drop random goodies upon destroying.'
