modLoader="javafml"
loaderVersion="[37,)"
license="GNU GPLv3"

[[mods]]
modId="tumbleweed"
version="1.17-0.4.10" # Remember to update in build.gradle
displayName="Tumbleweed"
logoFile="logo.png"
authors="konwboy"
description='Tumbleweeds spawn around dead bushes in deserts. They drop random goodies upon destroying.'
